### ISSUE TITLE
How can we invite new users? I need someone invited.

### ISSUE THREAD

**Issue by rsjazz** [jazz-community/ewm-scm-utils#2]
@SBI- I need spencermurata to be invited to the jazz-community organization.
At some point in time we should think about the ownership or adding admins.

**Comment by rsjazz** [comment]
I can't invite users, so I assume you have to @SBI-

**Comment by SBI-** [comment]
I've changed your role to owner on org-level, as you are by far the most active member. You should be able to invite people as you please. If you need anything else, just ping me here :)

**Comment by rsjazz** [comment]
Thank you so much!!!! @SBI-
